Feature/atualizar restaurante
TarcisioFls/reserva pull request #6
Opened 2024-09-11 01:47 UTC by WaldirJuniorGPN

2024-09-11 03:05 UTC, Henrique-Geenen approved these changes
CR Done!

2024-09-11 03:42 UTC, TarcisioFls approved these changes

2024-09-11 05:45 UTC, TarcisioFls requested changes

2024-09-11 05:45 UTC, TarcisioFls commented on src/main/java/br/com/grupo27/tech/challenge/reserva/application/controllers/restaurante/AtualizarRestauranteController.java
> +    @PutMapping("/{di}")
alterar o valor para id

2024-09-11 05:45 UTC, TarcisioFls commented on src/main/java/br/com/grupo27/tech/challenge/reserva/domain/presenters/restaurante/AtualizarRestaurantePresenterImpl.java
> +        return new Restaurante(atualizarRestauranteInput.getNome(), atualizarRestauranteInput.getDescricao(), atualizarRestauranteInput.getLocalizacao(), atualizarRestauranteInput.getHoraAbertura(),
Ao retornar esse restaurante vai ser necessário adicionar no construtor o id que foi adicionando no atualizarRestauranteInput, pois sem ele sempre irá criar um novo restaurante quando for atualizar

2024-09-12 01:34 UTC, Henrique-Geenen approved these changes

2024-09-12 02:36 UTC, TarcisioFls approved these changes

2024-09-12 13:29 UTC, rogeriosgomes approved these changes

2024-09-13 00:40 UTC, merged